import type { McpServerType } from './types'

export interface McpSuggestion {
  id: string
  name: string
  description: string
  type: McpServerType
  category: McpCategory
  command?: string
  args?: string[]
  url?: string
  icon: string
  popularity: number
}

export type McpCategory =
  | 'ai-agents'
  | 'developer-tools'
  | 'browser-automation'
  | 'database'
  | 'productivity'
  | 'search-data'
  | 'cloud-infra'
  | 'payments'
  | 'design'
  | 'observability'
  | 'automation'
  | 'analytics-seo'
  | 'communication'
  | 'media'

export const MCP_CATEGORY_LABELS: Record<McpCategory, string> = {
  'ai-agents': 'AI Agents',
  'developer-tools': 'Developer Tools',
  'browser-automation': 'Browser & Web',
  database: 'Database',
  productivity: 'Productivity',
  'search-data': 'Search & Data',
  'cloud-infra': 'Cloud & Infra',
  payments: 'Payments',
  design: 'Design',
  observability: 'Observability',
  automation: 'Automation',
  'analytics-seo': 'Analytics & SEO',
  communication: 'Communication',
  media: 'Media',
}

export const MCP_CATEGORY_ICONS: Record<McpCategory, string> = {
  'ai-agents': 'lucide:bot',
  'developer-tools': 'lucide:code-2',
  'browser-automation': 'lucide:globe',
  database: 'lucide:database',
  productivity: 'lucide:kanban',
  'search-data': 'lucide:search',
  'cloud-infra': 'lucide:cloud',
  payments: 'lucide:credit-card',
  design: 'lucide:palette',
  observability: 'lucide:activity',
  automation: 'lucide:workflow',
  'analytics-seo': 'lucide:bar-chart-3',
  communication: 'lucide:message-square',
  media: 'lucide:video',
}

export const MCP_SUGGESTIONS: McpSuggestion[] = [
  // ── AI Agents ──────────────────────────────────────────────
  {
    id: 'sug-codex',
    name: 'Codex CLI',
    description: 'Run OpenAI Codex as an MCP tool — create conversations and execute code',
    type: 'stdio',
    category: 'ai-agents',
    command: 'npx',
    args: ['-y', 'codex', 'mcp-server'],
    icon: 'lucide:terminal-square',
    popularity: 98,
  },
  {
    id: 'sug-claude-code',
    name: 'Claude Code',
    description: 'Run Claude Code in one-shot mode as an MCP tool for any LLM host',
    type: 'stdio',
    category: 'ai-agents',
    command: 'npx',
    args: ['-y', '@steipete/claude-code-mcp@latest'],
    icon: 'lucide:sparkles',
    popularity: 97,
  },
  {
    id: 'sug-sequential-thinking',
    name: 'Sequential Thinking',
    description: 'Structured step-by-step reasoning for complex problems',
    type: 'stdio',
    category: 'ai-agents',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    icon: 'lucide:brain',
    popularity: 93,
  },
  {
    id: 'sug-memory',
    name: 'Memory',
    description: 'Persistent knowledge graph — entities and relationships across sessions',
    type: 'stdio',
    category: 'ai-agents',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    icon: 'lucide:brain-circuit',
    popularity: 82,
  },
  {
    id: 'sug-memstate',
    name: 'Memstate AI',
    description: 'Versioned agent memory with conflict detection — track how decisions evolved',
    type: 'stdio',
    category: 'ai-agents',
    command: 'npx',
    args: ['-y', '@memstate/mcp'],
    icon: 'lucide:history',
    popularity: 71,
  },
  {
    id: 'sug-overture',
    name: 'Overture',
    description:
      "Visual plan approval — see your agent's plan as an interactive graph before code is written",
    type: 'stdio',
    category: 'ai-agents',
    command: 'npx',
    args: ['-y', 'overture-mcp'],
    icon: 'lucide:git-graph',
    popularity: 74,
  },

  // ── Browser & Web ──────────────────────────────────────────
  {
    id: 'sug-firecrawl',
    name: 'Firecrawl',
    description:
      'Web scraping and search — crawl sites, extract structured data, and convert to Markdown',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', 'firecrawl-mcp'],
    icon: 'lucide:flame',
    popularity: 88,
  },
  {
    id: 'sug-browserbase',
    name: 'Browserbase',
    description:
      'Cloud browser automation with Stagehand — navigation, extraction, and screenshots',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', '@browserbasehq/mcp-server-browserbase'],
    icon: 'lucide:cloud',
    popularity: 82,
  },
  {
    id: 'sug-playwright',
    name: 'Playwright',
    description: 'Browser automation using accessibility snapshots — fast and deterministic',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', '@anthropic/playwright-mcp'],
    icon: 'lucide:monitor-play',
    popularity: 96,
  },
  {
    id: 'sug-puppeteer',
    name: 'Puppeteer',
    description: 'Headless Chrome automation with screenshot and JS execution',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    icon: 'lucide:monitor',
    popularity: 85,
  },
  {
    id: 'sug-prompeteer',
    name: 'Prompeteer',
    description: 'Manage and expose reusable prompt templates for LLMs with variable support',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', 'mcp-teleprompter'],
    icon: 'lucide:scroll-text',
    popularity: 68,
  },
  {
    id: 'sug-snaprender',
    name: 'SnapRender',
    description: 'Screenshot API — capture any website in PNG, JPEG, WebP, or PDF',
    type: 'http',
    category: 'browser-automation',
    url: 'https://app.snap-render.com/mcp',
    icon: 'lucide:camera',
    popularity: 72,
  },
  {
    id: 'sug-crawl4ai',
    name: 'Crawl4AI',
    description: 'AI-powered web crawler — scrape, crawl, and extract structured data',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', 'mcp-crawl4ai-ts'],
    icon: 'lucide:spider',
    popularity: 74,
  },
  {
    id: 'sug-fetch',
    name: 'Fetch',
    description: 'Web page fetching and content extraction to Markdown',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-fetch'],
    icon: 'lucide:download',
    popularity: 83,
  },
  {
    id: 'sug-http-requests',
    name: 'HTTP Requests',
    description: 'Make outbound HTTP requests — REST APIs, JSON, custom headers',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', 'mcp-fetch-node'],
    icon: 'lucide:send',
    popularity: 70,
  },
  {
    id: 'sug-chrome-devtools',
    name: 'Chrome DevTools',
    description: 'Debug web pages — Console, Network, Performance Profiler',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', '@anthropic/chrome-devtools-mcp'],
    icon: 'lucide:inspect',
    popularity: 78,
  },
  {
    id: 'sug-apify',
    name: 'Apify',
    description: 'Web scraping, data extraction, and automation with 8,000+ ready-made Actors',
    type: 'http',
    category: 'browser-automation',
    url: 'https://mcp.apify.com',
    icon: 'lucide:spider',
    popularity: 80,
  },
  {
    id: 'sug-hyperbrowser',
    name: 'Hyperbrowser',
    description:
      'Scalable cloud browser automation for AI agents — scraping, navigation, and extraction',
    type: 'stdio',
    category: 'browser-automation',
    command: 'npx',
    args: ['-y', '@hyperbrowserai/mcp'],
    icon: 'lucide:globe',
    popularity: 72,
  },
  {
    id: 'sug-edgeone-pages',
    name: 'EdgeOne Pages',
    description: 'Deploy HTML to EdgeOne Pages and get a public URL instantly',
    type: 'http',
    category: 'browser-automation',
    url: 'https://mcp.edgeone.ai/mcp',
    icon: 'lucide:rocket',
    popularity: 52,
  },

  // ── Developer Tools ────────────────────────────────────────
  {
    id: 'sug-context7',
    name: 'Context7',
    description: 'Live, version-specific library docs injected into AI prompts',
    type: 'http',
    category: 'developer-tools',
    url: 'https://mcp.context7.com/mcp',
    icon: 'lucide:book-open',
    popularity: 100,
  },
  {
    id: 'sug-github',
    name: 'GitHub',
    description: 'Repos, issues, PRs, workflows, and code search',
    type: 'http',
    category: 'developer-tools',
    url: 'https://api.githubcopilot.com/mcp/',
    icon: 'lucide:github',
    popularity: 99,
  },
  {
    id: 'sug-filesystem',
    name: 'Filesystem',
    description: 'Secure local file read/write within allowed directories',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '.'],
    icon: 'lucide:folder',
    popularity: 95,
  },
  {
    id: 'sug-git',
    name: 'Git',
    description: 'Local repository manipulation — branches, commits, diffs',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-git'],
    icon: 'lucide:git-branch',
    popularity: 88,
  },
  {
    id: 'sug-gitlab',
    name: 'GitLab',
    description: 'Repository, CI/CD pipelines, and merge request integration',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-gitlab'],
    icon: 'lucide:git-merge',
    popularity: 72,
  },
  {
    id: 'sug-desktop-commander',
    name: 'Desktop Commander',
    description: 'Terminal access, process management, and ripgrep search',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@anthropic/desktop-commander-mcp'],
    icon: 'lucide:terminal',
    popularity: 80,
  },
  {
    id: 'sug-docker',
    name: 'Docker',
    description: 'Container management — build, run, inspect, and stop containers',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-docker'],
    icon: 'lucide:container',
    popularity: 70,
  },
  {
    id: 'sug-semgrep',
    name: 'Semgrep',
    description: 'Static analysis for security vulnerabilities and code quality',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@semgrep/mcp-server'],
    icon: 'lucide:shield-check',
    popularity: 62,
  },
  {
    id: 'sug-xcodebuildmcp',
    name: 'XcodeBuildMCP',
    description: 'Build, run, and test iOS/macOS apps — simulator control, screenshots, and logs',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', 'xcodebuildmcp@latest', 'mcp'],
    icon: 'lucide:hammer',
    popularity: 72,
  },
  {
    id: 'sug-docfork',
    name: 'Docfork',
    description: 'Up-to-date docs and code examples for any software library',
    type: 'http',
    category: 'developer-tools',
    url: 'https://mcp.docfork.com/mcp',
    icon: 'lucide:file-text',
    popularity: 76,
  },
  {
    id: 'sug-deepwiki',
    name: 'DeepWiki',
    description: 'Auto-generate architecture diagrams and docs for any codebase',
    type: 'http',
    category: 'developer-tools',
    url: 'https://mcp.deepwiki.com/mcp',
    icon: 'lucide:book-marked',
    popularity: 74,
  },
  {
    id: 'sug-firebase',
    name: 'Firebase',
    description: 'Work with Firebase projects — Firestore, Auth, Storage, and Cloud Functions',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', 'firebase-tools@latest', 'experimental:mcp'],
    icon: 'lucide:flame',
    popularity: 78,
  },
  {
    id: 'sug-e2b',
    name: 'E2B',
    description: 'Run code in secure cloud sandboxes — isolated execution for AI-generated code',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@e2b/mcp-server'],
    icon: 'lucide:box',
    popularity: 73,
  },
  {
    id: 'sug-storybook',
    name: 'Storybook',
    description: 'Write and test UI component stories automatically',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@storybook/addon-mcp'],
    icon: 'lucide:book-open-check',
    popularity: 68,
  },
  {
    id: 'sug-sonarqube',
    name: 'SonarQube',
    description: 'Code quality and security analysis — SAST, code smells, and coverage',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@sonarsource/sonarqube-mcp-server'],
    icon: 'lucide:shield-alert',
    popularity: 65,
  },
  {
    id: 'sug-circleci',
    name: 'CircleCI',
    description: 'CI/CD pipeline management — fix build failures and inspect workflows',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@circleci/mcp-server-circleci'],
    icon: 'lucide:circle-dot',
    popularity: 63,
  },
  {
    id: 'sug-buildkite',
    name: 'Buildkite',
    description: 'Manage Buildkite pipelines and builds from your editor',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@buildkite/mcp-server'],
    icon: 'lucide:hard-hat',
    popularity: 58,
  },
  {
    id: 'sug-jetbrains',
    name: 'JetBrains',
    description: 'Work on code with JetBrains IDEs — IntelliJ, WebStorm, PyCharm, and more',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@jetbrains/mcp-server'],
    icon: 'lucide:code-2',
    popularity: 74,
  },
  {
    id: 'sug-next-devtools',
    name: 'Next.js DevTools',
    description: 'Next.js development tools and utilities for AI coding assistants',
    type: 'stdio',
    category: 'developer-tools',
    command: 'npx',
    args: ['-y', '@vercel/next-devtools-mcp@latest'],
    icon: 'lucide:triangle',
    popularity: 70,
  },
  {
    id: 'sug-github-pr-analyser',
    name: 'GitHub PR & Issue Analyser',
    description: 'Analyse PRs, fetch diffs, create issues, manage tags and releases',
    type: 'stdio',
    category: 'developer-tools',
    command: 'uvx',
    args: ['https://github.com/saidsef/mcp-github-pr-issue-analyser.git'],
    icon: 'lucide:git-pull-request-arrow',
    popularity: 64,
  },
  {
    id: 'sug-github-projects-v2',
    name: 'GitHub Projects V2',
    description: 'Manage GitHub Projects V2 boards — items, fields, draft issues',
    type: 'stdio',
    category: 'developer-tools',
    command: 'uvx',
    args: ['mcp-github-projects'],
    icon: 'lucide:layout-dashboard',
    popularity: 58,
  },

  // ── Database ───────────────────────────────────────────────
  {
    id: 'sug-supabase',
    name: 'Supabase',
    description: 'Database, auth, storage, and realtime — full BaaS platform',
    type: 'http',
    category: 'database',
    url: 'https://mcp.supabase.com/mcp',
    icon: 'lucide:database',
    popularity: 94,
  },
  {
    id: 'sug-neon',
    name: 'Neon',
    description: 'Fully managed serverless PostgreSQL with branching',
    type: 'http',
    category: 'database',
    url: 'https://mcp.neon.tech/mcp',
    icon: 'lucide:database',
    popularity: 79,
  },
  {
    id: 'sug-postgresql',
    name: 'PostgreSQL',
    description: 'Direct Postgres access with read-only safety mode',
    type: 'stdio',
    category: 'database',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres'],
    icon: 'lucide:database',
    popularity: 90,
  },
  {
    id: 'sug-mongodb',
    name: 'MongoDB',
    description: 'Document database — schema inspection and JSON querying',
    type: 'stdio',
    category: 'database',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-mongodb'],
    icon: 'lucide:database',
    popularity: 75,
  },
  {
    id: 'sug-sqlite',
    name: 'SQLite',
    description: 'Local-first database queries and schema prototyping',
    type: 'stdio',
    category: 'database',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sqlite'],
    icon: 'lucide:database',
    popularity: 73,
  },
  {
    id: 'sug-redis',
    name: 'Redis',
    description: 'Caching, data structures, and pub/sub messaging',
    type: 'stdio',
    category: 'database',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-redis'],
    icon: 'lucide:database',
    popularity: 68,
  },
  {
    id: 'sug-clickhouse',
    name: 'ClickHouse',
    description: 'Query your ClickHouse OLAP database — fast analytics on large datasets',
    type: 'stdio',
    category: 'database',
    command: 'npx',
    args: ['-y', '@clickhouse/mcp-server'],
    icon: 'lucide:database',
    popularity: 66,
  },
  {
    id: 'sug-neo4j',
    name: 'Neo4j',
    description: 'Graph database — schema exploration, Cypher queries, and graph-backed memory',
    type: 'stdio',
    category: 'database',
    command: 'npx',
    args: ['-y', '@neo4j/mcp-server'],
    icon: 'lucide:share-2',
    popularity: 64,
  },
  {
    id: 'sug-chroma',
    name: 'Chroma',
    description: 'Embeddings, vector search, and document storage for AI applications',
    type: 'stdio',
    category: 'database',
    command: 'npx',
    args: ['-y', '@chroma-core/chroma-mcp'],
    icon: 'lucide:database',
    popularity: 62,
  },
  {
    id: 'sug-qdrant',
    name: 'Qdrant',
    description: 'Semantic memory layer on top of Qdrant vector search engine',
    type: 'stdio',
    category: 'database',
    command: 'npx',
    args: ['-y', '@qdrant/mcp-server-qdrant'],
    icon: 'lucide:database',
    popularity: 60,
  },

  // ── Search & Data ──────────────────────────────────────────
  {
    id: 'sug-brave-search',
    name: 'Brave Search',
    description: 'Privacy-focused web search with no tracking',
    type: 'stdio',
    category: 'search-data',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    icon: 'lucide:search',
    popularity: 79,
  },
  {
    id: 'sug-exa',
    name: 'Exa',
    description: 'AI-powered semantic search — find concepts, not just keywords',
    type: 'stdio',
    category: 'search-data',
    command: 'npx',
    args: ['-y', '@anthropic/exa-mcp-server'],
    icon: 'lucide:sparkles',
    popularity: 71,
  },
  {
    id: 'sug-tavily',
    name: 'Tavily',
    description: 'Real-time web search API built for AI agents',
    type: 'stdio',
    category: 'search-data',
    command: 'npx',
    args: ['-y', '@anthropic/tavily-mcp-server'],
    icon: 'lucide:search-check',
    popularity: 67,
  },
  {
    id: 'sug-perplexity',
    name: 'Perplexity',
    description: 'AI-native search with citation-rich answers for research',
    type: 'stdio',
    category: 'search-data',
    command: 'npx',
    args: ['-y', '@anthropic/perplexity-mcp-server'],
    icon: 'lucide:zap',
    popularity: 77,
  },
  {
    id: 'sug-reddit',
    name: 'Reddit',
    description: 'Fetch frontpage posts, subreddit info, hot posts, and comments',
    type: 'stdio',
    category: 'search-data',
    command: 'npx',
    args: ['-y', 'reddit-mcp-buddy'],
    icon: 'lucide:message-circle',
    popularity: 69,
  },
  {
    id: 'sug-coingecko',
    name: 'CoinGecko',
    description: 'Cryptocurrency prices, market data, and token info',
    type: 'http',
    category: 'search-data',
    url: 'https://mcp.coingecko.com/mcp',
    icon: 'lucide:bitcoin',
    popularity: 54,
  },

  {
    id: 'sug-kagi',
    name: 'Kagi Search',
    description: 'Ad-free web search with high-quality results via Kagi API',
    type: 'stdio',
    category: 'search-data',
    command: 'npx',
    args: ['-y', '@anthropic/kagi-mcp-server'],
    icon: 'lucide:search',
    popularity: 63,
  },
  {
    id: 'sug-serpapi',
    name: 'SerpApi',
    description: 'Google and other search engine results — SERP data for AI agents',
    type: 'stdio',
    category: 'search-data',
    command: 'npx',
    args: ['-y', '@serpapi/mcp-server'],
    icon: 'lucide:search-code',
    popularity: 60,
  },
  {
    id: 'sug-kaggle',
    name: 'Kaggle',
    description: 'Access datasets, models, competitions, notebooks, and benchmarks',
    type: 'stdio',
    category: 'search-data',
    command: 'npx',
    args: ['-y', '@kaggle/mcp-server'],
    icon: 'lucide:trophy',
    popularity: 65,
  },

  // ── Media ──────────────────────────────────────────────────
  {
    id: 'sug-elevenlabs',
    name: 'ElevenLabs',
    description: 'Text-to-speech, sound effects, voice cloning, and audio AI tools',
    type: 'stdio',
    category: 'media',
    command: 'npx',
    args: ['-y', '@elevenlabs/mcp-server'],
    icon: 'lucide:volume-2',
    popularity: 76,
  },
  {
    id: 'sug-transcriptor',
    name: 'Transcriptor',
    description: 'Video transcripts from YouTube, Twitter, TikTok, Vimeo, and more',
    type: 'stdio',
    category: 'media',
    command: 'npx',
    args: ['-y', 'transcriptor-mcp'],
    icon: 'lucide:subtitles',
    popularity: 66,
  },
  {
    id: 'sug-videodb',
    name: 'VideoDB',
    description: 'AI-driven video editing, semantic search, transcription, and content moderation',
    type: 'stdio',
    category: 'media',
    command: 'npx',
    args: ['-y', '@video-db/mcp-server'],
    icon: 'lucide:video',
    popularity: 58,
  },

  // ── Productivity ───────────────────────────────────────────
  {
    id: 'sug-notion',
    name: 'Notion',
    description: 'Pages, databases, comments, and workspace search',
    type: 'http',
    category: 'productivity',
    url: 'https://mcp.notion.com/mcp',
    icon: 'lucide:notebook',
    popularity: 89,
  },
  {
    id: 'sug-linear',
    name: 'Linear',
    description: 'Issue tracking, cycles, and project management',
    type: 'http',
    category: 'productivity',
    url: 'https://mcp.linear.app/mcp',
    icon: 'lucide:list-checks',
    popularity: 81,
  },
  {
    id: 'sug-asana',
    name: 'Asana',
    description: 'Projects, tasks, timelines, and team management',
    type: 'http',
    category: 'productivity',
    url: 'https://mcp.asana.com/mcp',
    icon: 'lucide:check-square',
    popularity: 69,
  },
  {
    id: 'sug-atlassian',
    name: 'Atlassian',
    description: 'Jira issues, Confluence pages, and DevOps workflows',
    type: 'http',
    category: 'productivity',
    url: 'https://mcp.atlassian.com/mcp',
    icon: 'lucide:ticket',
    popularity: 75,
  },
  {
    id: 'sug-intercom',
    name: 'Intercom',
    description: 'Customer support — conversations, contacts, and help center',
    type: 'http',
    category: 'productivity',
    url: 'https://mcp.intercom.com/mcp',
    icon: 'lucide:headphones',
    popularity: 58,
  },
  {
    id: 'sug-google-drive',
    name: 'Google Drive',
    description: 'Access Docs, Sheets, and Slides from Google Drive',
    type: 'stdio',
    category: 'productivity',
    command: 'npx',
    args: ['-y', '@anthropic/google-drive-mcp-server'],
    icon: 'lucide:hard-drive',
    popularity: 60,
  },
  {
    id: 'sug-plane',
    name: 'Plane',
    description: 'AI-native project management — work items, cycles, and modules',
    type: 'stdio',
    category: 'productivity',
    command: 'npx',
    args: ['-y', '@makeplane/plane-mcp-server'],
    icon: 'lucide:kanban',
    popularity: 56,
  },
  {
    id: 'sug-langfuse',
    name: 'Langfuse',
    description: 'Collaborative prompt editing, versioning, evaluating, and releasing',
    type: 'stdio',
    category: 'productivity',
    command: 'npx',
    args: ['-y', '@langfuse/mcp-server'],
    icon: 'lucide:file-edit',
    popularity: 62,
  },

  // ── Communication ──────────────────────────────────────────
  {
    id: 'sug-slack',
    name: 'Slack',
    description: 'Messages, channels, search, and team communication',
    type: 'stdio',
    category: 'communication',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-slack'],
    icon: 'lucide:message-square',
    popularity: 91,
  },
  {
    id: 'sug-twilio',
    name: 'Twilio',
    description: 'Send SMS, WhatsApp, and voice messages — manage phone numbers and accounts',
    type: 'stdio',
    category: 'communication',
    command: 'npx',
    args: ['-y', '@twilio/mcp-server'],
    icon: 'lucide:phone',
    popularity: 72,
  },
  {
    id: 'sug-resend',
    name: 'Resend',
    description: 'Send transactional emails directly from your editor',
    type: 'stdio',
    category: 'communication',
    command: 'npx',
    args: ['-y', '@resend/mcp-server'],
    icon: 'lucide:mail',
    popularity: 64,
  },
  {
    id: 'sug-mailgun',
    name: 'Mailgun',
    description: 'Email API — send, receive, and track email at scale',
    type: 'stdio',
    category: 'communication',
    command: 'npx',
    args: ['-y', '@mailgun/mcp-server'],
    icon: 'lucide:mail',
    popularity: 56,
  },

  // ── Payments ───────────────────────────────────────────────
  {
    id: 'sug-stripe',
    name: 'Stripe',
    description: 'Payments, subscriptions, invoices, and customer management',
    type: 'http',
    category: 'payments',
    url: 'https://mcp.stripe.com',
    icon: 'lucide:credit-card',
    popularity: 87,
  },
  {
    id: 'sug-paypal',
    name: 'PayPal',
    description: 'Invoices, payments, and transaction management',
    type: 'http',
    category: 'payments',
    url: 'https://mcp.paypal.com/http',
    icon: 'lucide:wallet',
    popularity: 61,
  },
  {
    id: 'sug-square',
    name: 'Square',
    description: 'Payment processing, inventory, and point-of-sale',
    type: 'http',
    category: 'payments',
    url: 'https://mcp.squareup.com/mcp',
    icon: 'lucide:square',
    popularity: 55,
  },

  // ── Cloud & Infra ──────────────────────────────────────────
  {
    id: 'sug-cloudflare',
    name: 'Cloudflare',
    description: 'Workers, KV, R2 storage, DNS, and edge config',
    type: 'http',
    category: 'cloud-infra',
    url: 'https://mcp.cloudflare.com/mcp',
    icon: 'lucide:cloud',
    popularity: 84,
  },
  {
    id: 'sug-vercel',
    name: 'Vercel',
    description: 'Deployments, logs, environments, and project management',
    type: 'stdio',
    category: 'cloud-infra',
    command: 'npx',
    args: ['-y', '@vercel/mcp-server'],
    icon: 'lucide:triangle',
    popularity: 82,
  },
  {
    id: 'sug-netlify',
    name: 'Netlify',
    description: 'Sites, build hooks, environment variables, and deploys',
    type: 'stdio',
    category: 'cloud-infra',
    command: 'npx',
    args: ['-y', '@netlify/mcp-server'],
    icon: 'lucide:globe',
    popularity: 69,
  },
  {
    id: 'sug-google-cloud',
    name: 'Google Cloud',
    description: 'Interact with Google Cloud services — compute, storage, and resource management',
    type: 'stdio',
    category: 'cloud-infra',
    command: 'npx',
    args: ['-y', '@google/cloud-mcp-server'],
    icon: 'lucide:cloud',
    popularity: 76,
  },
  {
    id: 'sug-azure',
    name: 'Azure',
    description: 'Manage and interact with Microsoft Azure services and resources',
    type: 'stdio',
    category: 'cloud-infra',
    command: 'npx',
    args: ['-y', '@azure/mcp-server'],
    icon: 'lucide:cloud',
    popularity: 74,
  },
  {
    id: 'sug-globalping',
    name: 'Globalping',
    description: 'Run network commands — ping, traceroute, DNS from worldwide probes',
    type: 'http',
    category: 'cloud-infra',
    url: 'https://mcp.globalping.io/mcp',
    icon: 'lucide:radar',
    popularity: 48,
  },

  // ── Design ─────────────────────────────────────────────────
  {
    id: 'sug-figma',
    name: 'Figma',
    description: 'Design-to-code, tokens, FigJam, and Dev Mode',
    type: 'http',
    category: 'design',
    url: 'https://mcp.figma.com/mcp',
    icon: 'lucide:figma',
    popularity: 86,
  },
  {
    id: 'sug-wix',
    name: 'Wix',
    description: 'Website builder — manage sites, pages, and content',
    type: 'http',
    category: 'design',
    url: 'https://mcp.wix.com/mcp',
    icon: 'lucide:layout',
    popularity: 50,
  },
  {
    id: 'sug-webflow',
    name: 'Webflow',
    description: 'Visual website builder — sites, CMS, and design tokens',
    type: 'http',
    category: 'design',
    url: 'https://mcp.webflow.com/mcp',
    icon: 'lucide:layout-template',
    popularity: 53,
  },

  // ── Observability ──────────────────────────────────────────
  {
    id: 'sug-sentry',
    name: 'Sentry',
    description: 'Real-time error tracking and performance monitoring',
    type: 'http',
    category: 'observability',
    url: 'https://mcp.sentry.dev',
    icon: 'lucide:bug',
    popularity: 83,
  },
  {
    id: 'sug-datadog',
    name: 'Datadog',
    description: 'Metrics, logs, traces, and full-stack observability',
    type: 'stdio',
    category: 'observability',
    command: 'npx',
    args: ['-y', '@datadog/mcp-server'],
    icon: 'lucide:activity',
    popularity: 70,
  },
  {
    id: 'sug-grafana',
    name: 'Grafana',
    description: 'Search dashboards, investigate incidents, and query datasources',
    type: 'stdio',
    category: 'observability',
    command: 'npx',
    args: ['-y', '@grafana/mcp-server'],
    icon: 'lucide:bar-chart-2',
    popularity: 72,
  },
  {
    id: 'sug-axiom',
    name: 'Axiom',
    description: 'Query and analyze logs, traces, and event data in natural language',
    type: 'stdio',
    category: 'observability',
    command: 'npx',
    args: ['-y', '@axiomhq/mcp-server-axiom'],
    icon: 'lucide:line-chart',
    popularity: 64,
  },
  {
    id: 'sug-logfire',
    name: 'Logfire',
    description: 'Access OpenTelemetry traces and metrics through Pydantic Logfire',
    type: 'stdio',
    category: 'observability',
    command: 'npx',
    args: ['-y', '@pydantic/logfire-mcp'],
    icon: 'lucide:flame-kindling',
    popularity: 58,
  },

  // ── Analytics & SEO ────────────────────────────────────────
  {
    id: 'sug-ahrefs',
    name: 'Ahrefs',
    description: 'Backlinks, keywords, traffic analysis, and competitor research',
    type: 'http',
    category: 'analytics-seo',
    url: 'https://api.ahrefs.com/mcp/mcp',
    icon: 'lucide:trending-up',
    popularity: 56,
  },

  // ── Automation ─────────────────────────────────────────────
  {
    id: 'sug-zapier',
    name: 'Zapier',
    description: 'Connect 7,000+ apps — trigger workflows across SaaS tools',
    type: 'http',
    category: 'automation',
    url: 'https://actions.zapier.com/mcp',
    icon: 'lucide:zap',
    popularity: 75,
  },
  {
    id: 'sug-make',
    name: 'Make',
    description: 'Turn Make scenarios into callable tools for AI assistants',
    type: 'stdio',
    category: 'automation',
    command: 'npx',
    args: ['-y', '@integromat/mcp-server'],
    icon: 'lucide:workflow',
    popularity: 68,
  },
]
